# Kubernetes 客户端API调用相关指令
---
# 查询名称为"default-token-****"的secrets，将截取的token添加到消息头，通过http调用restful API.
token:
 - APISERVER=$(kubectl config view | grep server | cut -f 2- -d ":" | tr -d " ")
 - TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')
 - "curl $APISERVER/api --header 'Authorization: Bearer $TOKEN' --insecure"


kubespray:
  link: https://github.com/kubernetes-sigs/kubespray/blob/master/docs/getting-started.md
  addNodes:
   - 在清单中增加节点
   - ansible-playbook -i inventory/mycluster/hosts.yml scale.yml -b -v --private-key=~/.ssh/private_key
  removeNodes:
   - ansible-playbook -i inventory/mycluster/hosts.yml remove-node.yml -b -v --private-key=~/.ssh/private_key --extra-vars "node=nodename,nodename2"
   - 节点不可达，在集群机器清单中增加主机变量 reset_nodes=no
