# Kubernetes 客户端API调用相关指令
---
# 查询名称为"default-token-****"的secrets，将截取的token添加到消息头，通过http调用restful API.
token:
 - APISERVER=$(kubectl config view | grep server | cut -f 2- -d ":" | tr -d " ")
 - TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')
 - "curl $APISERVER/api --header 'Authorization: Bearer $TOKEN' --insecure"
