---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-jenkins-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-volume
  local:
    path: /data/local/jenkins
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "local-volume"
spec:
  storageClassName: local-volume
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 150Gi