apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitlab-redis
  namespace: default
  labels:
    name: gitlab-redis
spec:
  replicas: 1
  selector:
      matchLabels:
        name: gitlab-redis
  template:
    metadata:
      name: gitlab-redis
      labels:
        name: gitlab-redis
    spec:
      containers:
        - name: gitlab-redis
          image: sameersbn/redis:4.0.9-2
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis
              name: data
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitlab-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-redis
  namespace: default
  labels:
    name: gitlab-redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    name: gitlab-redis