apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitlab-postgresql
  namespace: default
  labels:
    name: gitlab-postgresql
spec:
  replicas: 1
  selector:
      matchLabels:
        name: gitlab-postgresql
  template:
    metadata:
      name: gitlab-postgresql
      labels:
        name: gitlab-postgresql
    spec:
      containers:
        - name: postgresql
          image: sameersbn/postgresql:10-2
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              value: gitlab
            - name: DB_PASS
              value: gitlab
            - name: DB_NAME
              value: gitlab_production
            - name: DB_EXTENSION
              value: pg_trgm
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -U
                - postgres
            initialDelaySeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitlab-postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-postgresql
  namespace: default
  labels:
    name: gitab-postgresql
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    name: gitlab-postgresql