---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-redis-pvc
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "local-volume"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-gitlab-redis-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-volume
  local:
    path: /data/local/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master02

