istio-1.0.0:
  version: 1.0.0
  hub: 192.168.176.121:5000
  images:
    hyperkube:
      repo: quay.io/coreos
      tag: v1.7.6_coreos.0
    proxy_init:
      repo: istio
      tag: 1.0.0
    install-cni:
      repo: istio
      tag: 1.0.0
    node-agent-k8s:
      repo: istio
      tag: 1.0.0
    proxyv2:
      repo: istio
      tag: 1.0.0
    mixer:
      repo: istio
      tag: 1.0.0
    cert-manager-controller:
      repo: jetstack
      tag: v0.3.1
    pilot:
      repo: istio
      tag: 1.0.0
    all-in-one:
      repo: jaegertracing
      tag: "1.5"
    curl:
      repo: pstauffer
      tag: v1.0.3
    prometheus:
      repo: prom
      tag: v2.3.1
    galley:
      repo: istio
      tag: 1.0.0
    kiali:
      repo: kiali
      tag: istio-release-1.0
    sidecar_injector:
      repo: istio
      tag: 1.0.0
    servicegraph:
      repo: istio
      tag: 1.0.0
    grafana:
      repo: istio
      tag: 1.0.0
    citadel:
      repo: istio
      tag: 1.0.0


